version: "3.4"

services:
  trtdb:
    container_name: trtdb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  trt.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:DefaultConnection=mongodb://trtdb:27017"
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
    ports:
      - "8000:8080"
      - "8001:8081"
    depends_on:
      - trtdb
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  frontend-web:
    ports:
      - "3000:80"
    depends_on:
      - trt.api
